[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astlogdir => /var/log/asterisk
astrundir => /var/run/asterisk
astspooldir => /var/spool/asterisk

[options]
systemname = docker-pbx
runuser = asterisk
rungroup = asterisk
transmit_silence_during_record = yes

[files]
astctlpermissions = 0660
astctlowner = asterisk
astctlgroup = asterisk
