[general]
static = yes
writeprotect = no
clearglobalvars = no

[default]
exten => 1000,1,NoOp(Echo test from PBX for Dummies)
 same => n,Answer()
 same => n,Playback(hello-world)
 same => n,Echo()
 same => n,Hangup()
