[modules]
autoload = yes
noload = chan_sip.so
load = res_pjsip.so
load = res_pjsip_authenticator_digest.so
load = res_pjsip_endpoint_identifier_user.so
load = res_pjsip_logger.so
load = res_pjsip_messaging.so
load = res_pjsip_outbound_publish.so
load = res_pjsip_outbound_registration.so
load = res_pjsip_path.so
load = res_pjsip_phoneprov_provider.so
load = res_pjsip_pubsub.so
load = res_pjsip_session.so
load = res_http_websocket.so
load = chan_pjsip.so
